### ISSUE TITLE
Modifying character value creates NA values

### ISSUE THREAD

**Issue by UAB-BST-680** [UAB-BST-680/community#1]
I want to modify a character variable in a dataframe by replacing all "B" values with "C" values, but when I try to do this it turns the "B" values into NAs instead of "C":

``` r
df <- data.frame(x1 = c("A", "B"))

df$x1[2] <- "C"
#> Warning in `[<-.factor`(`*tmp*`, 2, value = structure(c(1L, NA), .Label =
#> c("A", : invalid factor level, NA generated

df
#>     x1
#> 1    A
#> 2 <NA>
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bcjaeger** [comment]
The issue is that `x1` is not a character vector but is a factor with levels "A" and "B".  R is forcing the intended value of "C" to NA because factors do not take values outside of their given levels and "C" is not in the set of {"A", "B"}. Here is how I would fix this: 

``` r
# set stringsAsFactors = FALSE to make df$x1 a character vector
df <- data.frame(x1 = c("A", "B"), stringsAsFactors = FALSE)

df$x1[2] <- "C"

df
#>   x1
#> 1  A
#> 2  C
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by UAB-BST-680** [comment]
That works, thank you!
